### ISSUE TITLE
Api dumps an error om screen when the json request body is too large

### ISSUE THREAD

**Issue by phpetra** [erfgoed-en-locatie/histograph#35]
Histograph API listening at port 3000
Error: request entity too large
    at makeError (/opt/histograph/io/node_modules/body-parser/node_modules/raw-body/index.js:184:15)
    at module.exports (/opt/histograph/io/node_modules/body-parser/node_modules/raw-body/index.js:40:15)
    at read (/opt/histograph/io/node_modules/body-parser/lib/read.js:64:3)
    at textParser (/opt/histograph/io/node_modules/body-parser/lib/types/text.js:78:5)
    at Layer.handle [as handle_request](/opt/histograph/io/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/opt/histograph/io/node_modules/express/lib/router/index.js:302:13)
    at /opt/histograph/io/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/opt/histograph/io/node_modules/express/lib/router/index.js:321:12)
    at next (/opt/histograph/io/node_modules/express/lib/router/index.js:261:10)
    at jsonParser (/opt/histograph/io/node_modules/body-parser/lib/types/json.js:103:37)
    at Layer.handle [as handle_request](/opt/histograph/io/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/opt/histograph/io/node_modules/express/lib/router/index.js:302:13)
    at /opt/histograph/io/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/opt/histograph/io/node_modules/express/lib/router/index.js:321:12)
    at next (/opt/histograph/io/node_modules/express/lib/router/index.js:261:10)
    at expressInit (/opt/histograph/io/node_modules/express/lib/middleware/init.js:23:5)

**Comment by bertspaan** [comment]
@phpetra did you experience this error lately?
