### ISSUE TITLE
Cavia plugin error?

### ISSUE THREAD

**Issue by wires** [erfgoed-en-locatie/histograph#62]
zoeken op `lijden` https://api.histograph.io/search?q=lijden geeft error

expand request:

```
{ uri: 'http://localhost:7474/histograph/expand',
  method: 'POST',
  json:
   { ids: [ 'urn:hgid:voc-opvarenden/123' ],
     equivalence: 'hg:sameHgConcept',
     hairs:
      [ 'hg:liesIn',
        'hg:originated',
        'hg:originatedFrom',
        'hg:absorbed',
        'hg:absorbedBy' ] } }
```

error:

```
TypeError: undefined is not a function
    at module.exports (/home/histograph/api/lib/geojson.js:35:22)
    at /home/histograph/api/index.js:59:26
    at /home/histograph/api/lib/query.js:98:11
    at Request._callback (/home/histograph/api/lib/graph.js:86:9)
    at Request.self.callback (/home/histograph/api/node_modules/request/request.js:197:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/home/histograph/api/node_modules/request/request.js:1050:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/home/histograph/api/node_modules/request/request.js:996:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

request.body

```

[[{"pit":{"name":"leijden","dataset":"poorterboeken","id":"urn:hgid:poorterboeken/1325","type":"hg:Place","data":{"currentPlaceName":"Leiden","provincie":"ZH"},"validSince":1636},"relations":[{"to":"urn:hg:tgn:7006809","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"van Leyden","dataset":"ilvb","id":"urn:hgid:ilvb/3416","type":"hg:Place","data":{"land":"Netherlands"},"validSince":1502,"validUntil":1503},"relations":[{"to":"urn:hg:geonames:2751773","type":"hg:sameHgConcept"},{"to":"urn:hg:tgn:7006809","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"leije","dataset":"poorterboeken","id":"urn:hgid:poorterboeken/1326","type":"hg:Place","data":{"currentPlaceName":"Leiden","provincie":"ZH"},"validSince":1640},"relations":[{"to":"urn:hg:tgn:7006809","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Leiden","dataset":"ilvb","id":"urn:hgid:ilvb/2030","type":"hg:Place","data":{"land":"Netherlands"},"validSince":1462,"validUntil":1508},"relations":[{"to":"urn:hg:tgn:7006809","type":"hg:sameHgConcept"},{"to":"urn:hg:geonames:2751773","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Leijden","dataset":"ilvb","id":"urn:hgid:ilvb/2031","type":"hg:Place","data":{"land":"Netherlands"},"validSince":1570,"validUntil":1571},"relations":[{"to":"urn:hg:geonames:2751773","type":"hg:sameHgConcept"},{"to":"urn:hg:tgn:7006809","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Leyen","dataset":"ilvb","id":"urn:hgid:ilvb/2054","type":"hg:Place","data":{"land":"Netherlands"},"validSince":1431,"validUntil":1557},"relations":[{"to":"urn:hg:geonames:2751773","type":"hg:sameHgConcept"},{"to":"urn:hg:tgn:7006809","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Leyen ?","dataset":"ilvb","id":"urn:hgid:ilvb/2055","type":"hg:Place","data":{"land":"Netherlands"},"validSince":1513,"validUntil":1514},"relations":[{"to":"urn:hg:geonames:2751773","type":"hg:sameHgConcept"},{"to":"urn:hg:tgn:7006809","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Leythen","dataset":"tgn","id":"urn:hg:tgn:term:1001180562","uri":"http://vocab.getty.edu/tgn/term/1001180562","type":"hg:Place","data":{"comment":"10th century"},"validSince":0900,"validUntil":1000},"relations":[{"to":"urn:hg:tgn:7006809","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Leiden","dataset":"tgn","id":"urn:hg:tgn:7006809","uri":"http://vocab.getty.edu/tgn/7006809","type":"hg:Place","geometry":{"type":"Point","coordinates":[4.5,52.15]}},"relations":[{"to":"urn:hg:tgn:7003632","type":"hg:liesIn"}],"hairs":[{"name":"Zuid-Holland","id":"urn:hg:tgn:7003632","uri":"http://vocab.getty.edu/tgn/7003632","type":"hg:Province"}]},{"pit":{"name":"Leyden","dataset":"ilvb","id":"urn:hgid:ilvb/2038","type":"hg:Place","data":{"land":"Netherlands"},"validSince":1451,"validUntil":1582},"relations":[{"to":"urn:hg:geonames:2751773","type":"hg:sameHgConcept"},{"to":"urn:hg:tgn:7006809","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Leyden in Hollant","dataset":"ilvb","id":"urn:hgid:ilvb/2039","type":"hg:Place","data":{"land":"Netherlands"},"validSince":1526,"validUntil":1527},"relations":[{"to":"urn:hg:geonames:2751773","type":"hg:sameHgConcept"},{"to":"urn:hg:tgn:7006809","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Leyen","dataset":"poorterboeken","id":"urn:hgid:poorterboeken/1348","type":"hg:Place","data":{"currentPlaceName":"Leiden","provincie":"ZH"},"validSince":1499},"relations":[{"to":"urn:hg:tgn:7006809","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Leyden","dataset":"tgn","id":"urn:hg:tgn:term:140366","uri":"http://vocab.getty.edu/tgn/term/140366-nl","type":"hg:Place"},"relations":[{"to":"urn:hg:tgn:7006809","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Leijde","dataset":"voc-opvarenden","id":"urn:hgid:voc-opvarenden/393","type":"hg:Place","validSince":1661,"validUntil":1791},"relations":[{"to":"urn:hg:geonames:2751773","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Leiden","dataset":"geonames","id":"urn:hg:geonames:2751773","uri":"http://sws.geonames.org/2751773","type":"hg:Place","geometry":{"type":"Point","coordinates":[4.49306,52.15833]},"data":{"featureClass":"P","featureCode":"PPL","countryCode":"NL","cc2":"","admin1Code":"11","admin2Code":"0546","admin3Code":"","admin4Code":""}},"relations":[{"to":"urn:hg:tgn:7006809","type":"hg:sameHgConcept"},{"to":"urn:hg:geonames:2751772","type":"hg:liesIn"}],"hairs":[{"name":"Gemeente Leiden","id":"urn:hg:geonames:2751772","uri":"http://sws.geonames.org/2751772","type":"hg:Municipality"}]},{"pit":{"name":"Lugdunum Batavorum","dataset":"tgn","id":"urn:hg:tgn:term:165241","uri":"http://vocab.getty.edu/tgn/term/165241","type":"hg:Place","data":{"comment":"invented by Janus Dousa in poems published in 1575"},"validSince":1575,"validUntil":1900},"relations":[{"to":"urn:hg:tgn:7006809","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Leijden","dataset":"voc-opvarenden","id":"urn:hgid:voc-opvarenden/5","type":"hg:Place","validSince":1635,"validUntil":1794},"relations":[{"to":"urn:hg:geonames:2751773","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Leyden","dataset":"poorterboeken","id":"urn:hgid:poorterboeken/1346","type":"hg:Place","data":{"currentPlaceName":"Leiden","provincie":"ZH"},"validSince":1493},"relations":[{"to":"urn:hg:tgn:7006809","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Leijen","dataset":"voc-opvarenden","id":"urn:hgid:voc-opvarenden/7379","type":"hg:Place","validSince":1701,"validUntil":1790},"relations":[{"to":"urn:hg:geonames:2751773","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"barrevelt van leyden","dataset":"poorterboeken","id":"urn:hgid:poorterboeken/195","type":"hg:Place","data":{"currentPlaceName":"Leiden","provincie":"ZH"},"validSince":1592},"relations":[{"to":"urn:hg:tgn:7006809","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"tot Leyen","dataset":"ilvb","id":"urn:hgid:ilvb/3268","type":"hg:Place","data":{"land":"Netherlands"},"validSince":1486,"validUntil":1487},"relations":[{"to":"urn:hg:tgn:7006809","type":"hg:sameHgConcept"},{"to":"urn:hg:geonames:2751773","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Leyde","dataset":"tgn","id":"urn:hg:tgn:term:328016","uri":"http://vocab.getty.edu/tgn/term/328016","type":"hg:Place"},"relations":[{"to":"urn:hg:tgn:7006809","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Leida","dataset":"tgn","id":"urn:hg:tgn:term:328015","uri":"http://vocab.getty.edu/tgn/term/328015","type":"hg:Place"},"relations":[{"to":"urn:hg:tgn:7006809","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"leiden","dataset":"poorterboeken","id":"urn:hgid:poorterboeken/1322","type":"hg:Place","data":{"currentPlaceName":"Leiden","provincie":"ZH"},"validSince":1537},"relations":[{"to":"urn:hg:tgn:7006809","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Lijen","dataset":"voc-opvarenden","id":"urn:hgid:voc-opvarenden/13942","type":"hg:Place","validSince":1712,"validUntil":1790},"relations":[{"to":"urn:hg:geonames:2751773","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Leiden","dataset":"kloeke","id":"urn:hg:kloeke:E167p","uri":"http://www.meertens.knaw.nl/kloeke/index.php?kloekenummer=E167p","type":"hg:Place","geometry":{"type":"Point","coordinates":[4.49694981821,52.1675413303]},"data":{"Kloeke code oud":"E 167"}},"relations":[{"to":"urn:hg:geonames:2751773","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Leiden","dataset":"tgn","id":"urn:hg:tgn:term:48434","uri":"http://vocab.getty.edu/tgn/term/48434-nl","type":"hg:Place"},"relations":[{"to":"urn:hg:tgn:7006809","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Lijden","dataset":"voc-opvarenden","id":"urn:hgid:voc-opvarenden/123","type":"hg:Place","validSince":1681,"validUntil":1794},"relations":[{"to":"urn:hg:geonames:2751773","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Matilo","dataset":"pleiades","id":"urn:hg:pleiades:99008/matilo","uri":"http://pleiades.stoa.org/places/99008/matilo","type":"hg:Place","geometry":{"type":"Point","coordinates":[4.518428,52.150265]},"data":{"geoContext":"Leiden","featureType":"fort"}},"relations":[{"to":"urn:hg:geonames:2751773","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Leyen, Leyden","dataset":"ilvb","id":"urn:hgid:ilvb/2061","type":"hg:Place","data":{"land":"Netherlands"},"validSince":1529,"validUntil":1530},"relations":[{"to":"urn:hg:geonames:2751773","type":"hg:sameHgConcept"},{"to":"urn:hg:tgn:7006809","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Leiden","dataset":"voc-opvarenden","id":"urn:hgid:voc-opvarenden/182","type":"hg:Place","validSince":1683,"validUntil":1794},"relations":[{"to":"urn:hg:geonames:2751773","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Leide","dataset":"voc-opvarenden","id":"urn:hgid:voc-opvarenden/8786","type":"hg:Place","validSince":1734,"validUntil":1790},"relations":[{"to":"urn:hg:geonames:2751773","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Lijde","dataset":"voc-opvarenden","id":"urn:hgid:voc-opvarenden/2683","type":"hg:Place","validSince":1693,"validUntil":1777},"relations":[{"to":"urn:hg:geonames:2751773","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Leyden","dataset":"voc-opvarenden","id":"urn:hgid:voc-opvarenden/2125","type":"hg:Place","validSince":1700,"validUntil":1792},"relations":[{"to":"urn:hg:geonames:2751773","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"buyten Leyden","dataset":"ilvb","id":"urn:hgid:ilvb/565","type":"hg:Place","data":{"land":"Netherlands"},"validSince":1506,"validUntil":1507},"relations":[{"to":"urn:hg:geonames:2751773","type":"hg:sameHgConcept"},{"to":"urn:hg:tgn:7006809","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Lyen","dataset":"ilvb","id":"urn:hgid:ilvb/2161","type":"hg:Place","data":{"land":"Netherlands"},"validSince":1477,"validUntil":1478},"relations":[{"to":"urn:hg:geonames:2751773","type":"hg:sameHgConcept"},{"to":"urn:hg:tgn:7006809","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"in Leyen","dataset":"ilvb","id":"urn:hgid:ilvb/1865","type":"hg:Place","data":{"land":"Netherlands"},"validSince":1501,"validUntil":1502},"relations":[{"to":"urn:hg:tgn:7006809","type":"hg:sameHgConcept"},{"to":"urn:hg:geonames:2751773","type":"hg:sameHgConcept"}],"hairs":[]},{"pit":{"name":"Hogelant, Leyen","dataset":"ilvb","id":"urn:hgid:ilvb/1669","type":"hg:Place","data":{"land":"Netherlands"},"validSince":1479,"validUntil":1480},"relations":[{"to":"urn:hg:tgn:7006809","type":"hg:sameHgConcept"},{"to":"urn:hg:geonames:2751773","type":"hg:sameHgConcept"}],"hairs":[]}]]

```

**Comment by bertspaan** [comment]
TGN PIT:

`{"uri":"http://vocab.getty.edu/tgn/term/1001180562","name":"Leythen","type":"hg:Place","data":{"comment":"10th century"},"validSince":"0900","validUntil":"1000"}`

Somewhere in chain IO - Core - Graphmalizer, date string `"0900"` is parsed as a JSON string one time too many.

**Comment by bertspaan** [comment]
Histograph IO pushes on Redis queue correctly:
- PIT example 1

``` json
{"uri":"http://waag.org/test/3","name":"Test 3","type":"hg:Place","validSince":[1500, 1600]}
```
- Redis queue (`redis-cli lindex histograph 2 | python -mjson.tool`):

``` json
{
    "action": "add",
    "data": {
        "name": "Test 3",
        "type": "hg:Place",
        "uri": "http://waag.org/test/3",
        "validSince": [
            1500,
            1600
        ]
    },
    "dataset": "test",
    "type": "pit"
}
```
- PIT example 2: 

``` json
{"uri":"http://waag.org/test/4","name":"Test 4","type":"hg:Place","validSince": "0800"}
```
- Redis queue (`redis-cli lindex histograph 3 | python -mjson.tool`):

``` json
{
    "action": "add",
    "data": {
        "name": "Test 4",
        "type": "hg:Place",
        "uri": "http://waag.org/test/4",
        "validSince": "0800"
    },
    "dataset": "test",
    "type": "pit"
}
```
